from __future__ import annotations

from .artifacts import save_edit_condition_artifacts, save_preprocessed_inputs
from .asset_3d import (
    MaskGLBResult,
    VoxelNormalization,
    coords_to_flat_indices,
    coords_to_voxel,
    feats_to_slat,
    load_mask_glb_coords,
    load_ply_positions,
    load_source_voxel_normalization,
    ply_to_coords,
    project_sparse_terminal_noise,
    sparse_batch_slice,
)
from .foreground_scale_selection import (
    ActiveBBox,
    build_square_crop_box,
    compute_active_bbox,
    compute_sparse_structure_metrics,
    normalize_sparse_coords,
    select_crop_scale_from_linear_fit,
    select_crop_scale_from_probes,
)
from .image_alignment import (
    PROC_IMAGE_SIZE,
    CropContext,
    PreparedEditCondition,
    PreparedInputs,
    build_union_crop_context,
    composite_rgb_from_rgba,
    extract_foreground_rgba,
    has_useful_alpha,
    prepare_aligned_inputs,
    prepare_edit_condition_image,
    scale_image,
)
from .mask_utils import build_auto_mask, build_blank_mask, binarize_mask_image, extract_mask_channel
from .source_assets import (
    ensure_source_assets,
    generate_source_assets_from_image,
    generate_source_assets_from_model,
)

__all__ = [
    "MaskGLBResult",
    "PROC_IMAGE_SIZE",
    "ActiveBBox",
    "CropContext",
    "PreparedEditCondition",
    "PreparedInputs",
    "VoxelNormalization",
    "binarize_mask_image",
    "build_auto_mask",
    "build_blank_mask",
    "build_square_crop_box",
    "build_union_crop_context",
    "compute_active_bbox",
    "compute_sparse_structure_metrics",
    "composite_rgb_from_rgba",
    "coords_to_flat_indices",
    "coords_to_voxel",
    "ensure_source_assets",
    "extract_foreground_rgba",
    "extract_mask_channel",
    "feats_to_slat",
    "generate_source_assets_from_image",
    "generate_source_assets_from_model",
    "has_useful_alpha",
    "load_mask_glb_coords",
    "load_ply_positions",
    "load_source_voxel_normalization",
    "normalize_sparse_coords",
    "ply_to_coords",
    "prepare_aligned_inputs",
    "prepare_edit_condition_image",
    "project_sparse_terminal_noise",
    "save_edit_condition_artifacts",
    "save_preprocessed_inputs",
    "scale_image",
    "select_crop_scale_from_linear_fit",
    "select_crop_scale_from_probes",
    "sparse_batch_slice",
]
